### ISSUE TITLE
Support for all AWS partitions

### ISSUE THREAD

**Issue by burdzwastaken** [zalando-incubator/kube-aws-iam-controller#37]
Currently the controller hard codes the [`arnPrefix`](https://github.com/zalando-incubator/kube-aws-iam-controller/blob/master/credentials_getter.go#L16) making it not possible to use it within environments such as AWS GovCloud where the ARN prefix differs: e.g. `arn:aws-us-gov:iam::`. 

I am happy to create a patch but wondered how you would want this implemented as I see two directions:
- User provided via a flag making it the operators duty to toggle the configuration in alternative partitions
- Parsed from the user provided or autodiscovered base role ARN

Let me know if you have any thoughts or ideas regarding the implementation details.

Thanks for the great project!

**Comment by burdzwastaken** [comment]
any update on the above ^^.

**Comment by mikkeloscar** [comment]
Sorry, I forgot about this one :(

Parsing it based on the base role ARN seems like the best to me, then it's either completely automatic or the operator only has to parse a custom `base-role-arn` and not also the ARN prefix.

PR's very welcome!
