### ISSUE TITLE
Is support for JS AWS SDK available?

### ISSUE THREAD

**Issue by usepe** [zalando-incubator/kube-aws-iam-controller#42]
As seen in this PR: https://github.com/aws/aws-sdk-js/pull/1923

It does seem they merged the support for `credential_process`, but in  https://github.com/zalando-incubator/kube-aws-iam-controller/blob/master/docs/sdk-configuration.md does not seem to be yet available the version in which they put it

Can someone with knowledge on this specific SDK clarify this?

Thanks!

**Comment by mikkeloscar** [comment]
I tested the js sdk a while back, and while the particular PR was merged, it seemed like it didn't work. I didn't end up tracking down the issue, but I think it was a bug in the sdk. So unless something has changed in the SDK I believe it still doesn't work, unfortunately.

**Comment by usepe** [comment]
Thanks for answering @mikkeloscar
