### ISSUE TITLE
Taking control of seed credential

### ISSUE THREAD

**Issue by mikesir87** [zalando-incubator/kube-aws-iam-controller#50]
When running in a non-AWS environment, we have to seed a credential in the system. Ideally, it would be great for that credential to then be managed by the controller so it gets auto-rotated. These are the steps I took to make it work, but wanted to check with you all to see if this is the anticipated route (or talk about another route).

1. I first created the seed credential named `kube-aws-iam-controller`
1. I created an `AWSIAMRole` with the same name in the same namespace (in my case, `kube-aws-iam-controller`)
1. When the controller sees the role, it tries to create credentials, but can't because:

    ```
    reason: 'CreateSecretFailed' Failed to create secret kube-system/kube-aws-iam-controller-iam-role with credentials: secrets \"kube-aws-iam-controller-iam-role\" already exists"
    ```

1. Looking at the source, I found that you use a label named `heritage` with a value of `kube-aws-iam-controller` to know the secret is being managed by the controller. I added this label to the seed secret.
1. The controller then sees the secret doesn't have an `expire` key, so auto-rotates the credential.

Since then, I seem to be in a stable state. But, I fully recognize labels aren't normally part of public API, so are subject to change. Is there another approach I should take or any recommendations on a route to "adopt an existing secret"?

**Comment by mikkeloscar** [comment]
@mikesir87 This is the right way to do it. One additional thing would be to add the `ownerReferences` to the Secret such that it's marked to be owned by the `AWSIAMRole` resource. Look at other secrets created by the controller to see how it's done if you're not familiar with it.
